name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    
    - name: Set GOPATH
      run: |
        echo "##[set-env name=GOPATH;]$(dirname $GITHUB_WORKSPACE)"
        echo "##[add-path]$(dirname $GITHUB_WORKSPACE)/bin"
        shell: bash

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Install dep
      run:
        curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        
    - name: Install dependencies
      run: 
        dep ensure
        
    - name: Run tests
      run: go test -v
    

    - name: Build
      run: go build -v .
      
